# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/" # Library Crate - This includes Workspace crates tests-common and utils based on the root Cargo.toml
      - "/examples/*"
      - "/tests/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
