services:
  github_runner:
    build:
      context: ./github-runner-dockerfile
      dockerfile: Dockerfile
    container_name: github_runner
    environment:
      - REPO=dysonltd/tmag5273
      - TOKEN="" # Fill this in
    restart: always
    networks:
      - default
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - default