# This Docker Compose File is for setting up the Hardware in the Loop Test Bench
---

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - default

  github_runner:
    image: myoung34/github-runner
    container_name: github_runner
    environment:
      - REPO_URL=https://github.com/dysonltd/tmag5273
      - RUNNER_TOKEN=${GHA_TOKEN}
      - RUN_AS_ROOT=true
      - LABELS=self-hosted, RPI5
    restart: always
volumes:
  portainer_data: