services:
  github_runner:
    build:
      context: ./github-runner-dockerfile
      dockerfile: Dockerfile
    container_name: github_runner
    environment:
      - REPO=dysonltd/tmag5273
      - TOKEN="" # Fill this in
    restart: always
    networks:
      - default
