---
    name: Linting
    
    on: # yamllint disable-line rule:truthy
      # push: null
      pull_request: null
    
    permissions: {}
    
    jobs:
      Super_Linter:
        name: Super Linter
        runs-on: ubuntu-latest
    
        permissions:
          contents: read
          packages: read
          # To report GitHub Actions status checks
          statuses: write
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              # super-linter needs the full git history to get the
              # list of files that changed across commits
              fetch-depth: 0
    
          - name: Super-linter
            uses: super-linter/super-linter@v7.2.0 # x-release-please-version
            env:
              # Linters
              VALIDATE_MARKDOWN: true
              VALIDATE_RUST_CLIPPY: true
              VALIDATE_YAML: true
              # Auto Fix the files
              FIX_RUST_CLIPPY: true
              FIX_MARKDOWN: true
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
      Formatter:
        name: Formatter
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4  
          - name: Rustfmt
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              override: true
            env:
              RUSTUP_HOME: ${{ runner.temp }}/rustup
              CARGO_HOME: ${{ runner.temp }}/cargo
          - name: Rustfmt check
            run: cargo fmt -- --check
          - name: Rustfmt format
            run: cargo fmt